.dockerignore, .gitignore
This ignores the .idea directory that gets created when opening the project with the Jetbrains GoLand IDE.
I have a thoery that the .gitignore file was created on windows without the `git config --global core.autocrlf true` set.
=> Ignore .idea directory

CHANGELOG.md, artifact.go
Doing this:
```go
type TestsResults struct {
Passed, Failed int
Status         string
}
```
While it's a valid Go type with 3 different fields, the `swag init` generated the following:
```yaml
main.TestsResults:
properties:
passed:
type: integer
status:
type: string
type: object
```
These changes turns it into this schema:
```yaml
main.TestsResults:
properties:
failed:
type: integer
passed:
type: integer
status:
enum:
- Success
- Failed
- No tests
type: string
type: object
```
=> Fixed JSON schema for main.TestsResults

CHANGELOG.md, provider.go
This adds a code path for PUT for /api/provider
This goes together with a few other PRs:
- The implementable interface https://github.com/iver-wharf/wharf-api-client-go/pull/8
- The PUT /api/token https://github.com/iver-wharf/wharf-api/pull/26
- (This) The PUT /api/provider https://github.com/iver-wharf/wharf-api/pull/28
- The gtihub-provider changes that require the rest https://github.com/iver-wharf/wharf-provider-github/pull/10
=> Add endpoint PUT /provider

CHANGELOG.md, token.go
This adds a code path for PUT for `/api/token`
This goes together with a few other PRs:
- The implementable interface https://github.com/iver-wharf/wharf-api-client-go/pull/8
- (This) The PUT /api/token https://github.com/iver-wharf/wharf-api/pull/26
- The PUT /api/provider https://github.com/iver-wharf/wharf-api/pull/28
- The gtihub-provider changes that require the rest https://github.com/iver-wharf/wharf-provider-github/pull/10
=> Add endpoint PUT /token

CHANGELOG.md, Dockerfile
Got a vulnerability warning from quay.io:
> CVE-2021-30139: https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2021-30139
> CVE-2020-28928: https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2020-28928
>
> https://quay.io/repository/iver-wharf/wharf-api/manifest/sha256:d2d805a6ee9d4a99b5a759b9b15fde617f4e66b5952b70d7539118b05e42eadf?tab=vulnerabilities
This is a wild guess if that fixes it. Just assuming.
=> Updated Alpine Docker image to 3.13.5

CHANGELOG.md, go.mod, go.sum
Bug with foreign keys was fixed in v1.21.10: https://github.com/go-gorm/gorm/issues/4316
As well as a regression bug in v1.21.10: https://github.com/go-gorm/gorm/issues/4386
The project now works fine with latest version of GORM.
=> GORM v1.21.11

CHANGELOG.md, artifact.go, branch.go, build.go, database.go, go.mod, go.sum, main.go, migrations.go, pkg/httputils/httpclient.go, project.go
This just replaces the previous logging via logrus and `fmt.Print` with the new logging introduced in iver-wharf/wharf-core#10. No additional logging has been added nor has any been removed.
- Replaced logrus with wharf-core logging
- Replaced fmt.Print usage with wharf-core logging
=> Logging via wharf-core

CHANGELOG.md, Dockerfile
Go: v1.16.4 -> v1.16.5
Alpine: v3.13.5 -> v3.14.0
=> Updated golang & alpine Docker images

CHANGELOG.md, Dockerfile, Makefile, README.md
- Updated Dockerfile with labels based on https://github.com/projectatomic/ContainerApplicationGenericLabels
- Updated Dockerfile to abuse Docker layer caching for go.mod & go.sum files
- Added Makefile and moved some dependency downloading and Swagger generation over there, as well as Docker build command
Fulfilling what was started in iver-wharf/wharf-provider-github#24:
> This will simplify things so we just keep track of having to do make swag instead of all the --parseDependency --parseDepth stuff.
> 
> Also, some of the Dockerfile changes makes it so the build uses the Docker cache more efficiently, leading to faster consequitive …
=> Added Makefile

CHANGELOG.md, Dockerfile
This change will allow setting timezone from the environment variable ex. TZ=Europe/Stockholm. 
Changing the timezone can be relevant during certain types of key/signature checks. 
Similar PRs opened for the other imaged repos:
https://github.com/iver-wharf/wharf-provider-github/pull/25
https://github.com/iver-wharf/wharf-provider-azuredevops/pull/20
https://github.com/iver-wharf/wharf-provider-gitlab/pull/20
https://github.com/iver-wharf/wharf-api/pull/40
=> Add tzdata package to prod container

CHANGELOG.md, Makefile
- `make docker` only echo'd `docker build` and did not actually run it. Technically called a "boo boo" from my end.
It did go through review, so I mean, we're all to blame :)
=> Fixed Makefile docker build

CHANGELOG.md, database.go, go.mod, go.sum, main.go
- Added missing wharf-core logging integration for DB on initialization.
- Updated wharf-core to get those new easier to read logs via iver-wharf/wharf-core#23
Finalizing the logging integration. Now wharf-api is properly set up to use wharf-core's logging
=> Using wharf-core v1.1.0 logging throughout

CHANGELOG.md, artifact.go, branch.go, build.go, buildstatus.go, database.go, database_models.go, main.go, module.go, ping.go, pkg/orderby/direction.go, pkg/orderby/orderby.go, project.go, project_test.go, provider.go, token.go
- Changed a lot of types & functions from exported to unexported.
- Documented the remaining exported types that needs to be exported, such as JSON responses and DB models.
We start growing error fatigue due to the existing errors. Broken window principle applies here.
If we have properly commented everything, it'll be easier to see how we should keep it, and it's be less insentive to just ignore the linting errors.
=> Documented remaining values

CHANGELOG.md, go.mod, main.go, messagequeue.go, ping.go
Added `/api/health` and `/api/ping` endpoints, in preparation of removing the `/health` and `/` endpoints respectively.
The `/health` and `/` endpoints were not accessible through the Swagger API, as it tried to send requests to `/api/health` and `/api/ping` instead. This fixes that issue, and has all endpoints in the same group, i.e. `/api`.
=> Added /api/health and /api/ping endpoints

CHANGELOG.md, Dockerfile, Makefile, go.mod
Swaggo v1.7.1, thereby eliminating the dependecy on the alecthomas/template package.
Stay up-to-date
=> Swaggo/swag v1.7.1

CHANGELOG.md, config.go
Comment seems to have ended mid-sentence. I completed it based on the discussion over at https://github.com/iver-wharf/wharf-provider-gitlab/pull/23#pullrequestreview-736934503
Keeping docs relevant.
=> Fixed AllowAllOrigins doc comment

CHANGELOG.md, project.go
- Removed `cannot-change-group` constraint from `PUT /project`
The constraint is somewhat arbitrary and lacks motivation.
Also, for the migrations needed for https://github.com/iver-wharf/rfcs/pull/17 then this constraint would've been in the way.
=> Removed constraint of "cannot change group"

CHANGELOG.md, build.go, buildstatus.go, database.go, database_models.go, database_models_json.go, database_models_json_test.go, utils.go, utils_test.go
- Fixed regression introduced in #46 where `Project.MarshalJSON` and `Build.MarshalJSON` were renamed, unknowing that it broke the Go interface [`Marshaler`](https://pkg.go.dev/encoding/json#Marshaler) from the `encoding/json` package.
This lead to the `GET /projects` and `GET /project/{projectid}` to not have their parsed build definitions, that are needed in the wharf-web.
- Fixed bug where if it silently ignored failing status parsing
This still regards unreleased changes, so I've not added a dedicated release note for it.
The refactoring was made to try and make it clearer that this marshalling is being done, as @Alexamakans spent hours …
=> Fixed project & build JSON marshal regression

CHANGELOG.md, Dockerfile
- Removed the patch version from Docker base images, as that will use the latest patch version instead.
Leads to fewer vulnerabilities to stay on "latest", while still not getting failing builds due to breaking changes in version bumps.
This also fixes the following vulnerabilities:
```console
$ trivy i -i v4.2.0-rc.1.tar
2021-09-09T08:54:56.799+0200	INFO	Detected OS: alpine
2021-09-09T08:54:56.799+0200	INFO	Detecting Alpine vulnerabilities...
2021-09-09T08:54:56.799+0200	INFO	Number of language-specific files: 1
2021-09-09T08:54:56.799+0200	INFO	Detecting gobinary vulnerabilities...
v4.2.0-rc.1.tar (alpine 3.14.0) …
```
=> Rely on Docker images latest patch version

CHANGELOG.md
- \[x] I've updated the `(WIP)` tag to today's date in `CHANGELOG.md`
- \[x] I've added the `release` label to this PR
Same as for #58
I forgot to update the date in the CHANGELOG.md before merging. Again.
Follow the step-by-step guide found here:
<https://iver-wharf.github.io/#/development/releasing-a-new-version?id=merging-a-release-pr>
=> Release v4.2.0 (with fixed date)

CHANGELOG.md, main.go
- Moved `gin.DefaultWriter` assignment to before `gin.New()` is called.
`gin.New()` can do some logging, such as the following log message:
```log
[GIN-debug] [WARNING] Running in "debug" mode. Switch to "release" mode in production.
- using env:	export GIN_MODE=release
- using code:	gin.SetMode(gin.ReleaseMode)
```
This fixes that so it uses wharf-core logger for that as well.
=> Fixed so gin logger intration is setup before it's used

Makefile
- Added `--pull` to `docker build` in `Makefile`
This forces the docker build to always try and pull the latest image, so that our local cache doesn't make our newly-built images use old base images.
[The `--pull` flag](https://docs.docker.com/engine/reference/commandline/build/#:~:text=--pull) does not disable the cache. Docker will first check the hashes of the upstream image layers, and only if they don't match with the cached layers then it will start downloading the up-to-date layers.
This was brought up in a PR discussion: https://github.com/iver-wharf/wharf-web/pull/66#discussion_r706091268
---
Skipping adding to CHANGELOG.md as this …
=> Added "--pull" to docker build

CHANGELOG.md, database_models.go, migrations.go
Changed the constraint behavior between Project and all its children (Branch, Build, BuildParam, Log, Artifact) to `CASCADE` instead of `RESTRICT`, so that we can delete/update a Project without having to do it to the data that is lower in the hierarchy manually.
Closes #62
=> Fixed cannot delete projects

CHANGELOG.md, artifact.go, branch.go, build.go, project.go, provider.go, test_result.go, token.go
- `branchid` &rarr; `branchId`
- `projectid` &rarr; `projectId`
- `providerid` &rarr; `providerId`
- `tokenid` &rarr; `tokenId`
- `buildid` &rarr; `buildId`
I did a search and replace on all files inside the repo. No all-lowercase alternatives, except for inside the CHANGELOG.md, remain.
Closes #68
=> Changed path params to camelCase

CHANGELOG.md, artifact.go, database_models.go
Changed the comment for `artifactModule.getBuildTestsResultsHandler` so that it refers to the correct endpoint.
Fixed a typo in `TestResultDetail` field tags, `enums` changed to `enum`.
Fixed constraint behavior definition for `Build.TestResultSummaries`.
Being pointed to a non-existing endpoint when something is deprecated isn't a great thing, this prevents anybody experiencing that.
The typo made it so the `status` field generated over at [iver-wharf/wharf-api](https://github.com/iver-wharf/wharf-api) was of type `MainTestResultDetail` instead of `string`, causing some issues with simple integration.
The constraint behavior definition was …
=> Fixed some things missed in PR #43

CHANGELOG.md, artifact.go, branch.go, build.go, database_models.go, migrations.go, pkg/model/database/database.go, pkg/model/request/request.go, pkg/model/response/response.go, project.go, provider.go, token.go
- Added packages
- `pkg/model/database`
- `pkg/model/request`
- `pkg/model/response`
- Changed usage of `{type}Field{FieldName}` to `database.{Type}Fields.{FieldName}`
- Updated `token.go` to use new models
- Updated migrations to use new models
- Added transaction to PUT token and made it associate with the provider by the ID from the request JSON.
Related to #72, but doesn't close it yet as there are a lot more files to be dealt with.
This is like a taste sample. Better to get feedback on this early, as changing the remaining files will result in a giant PR that does pretty much the same stuff everywhere.
The -Search model will remain until …
=> Split up DB models: part 1

CHANGELOG.md, artifact.go, branch.go, build.go, ping.go, project.go, provider.go, test_result.go, token.go, version.go
- Added Swaggo `// @id` comment field, which adds Swagger operation IDs to the endpoints.
- Changed name of Gin handler methods to correlate with the new Swagger op IDs
Closes #67
=> Added swaggo operation ID & renamed handlers

CHANGELOG.md, branch.go, build.go, database_models.go, pkg/model/database/database.go, project.go
Added `Build.TestResultListSummary` field.
This field is manually populated when fetching a `Build`, using the function `populateTestResultListSummary` located in `build.go`.
Changed so `Build.TestResultSummaries` is preloaded in `buildModule.getBuild` and `projectModule.getBuilds`.
One big part of the test result handling rework (#43) was to fix N+1 Select issue(s) in [wharf-web](https://github.com/iver-wharf/wharf-web), but I seem to have mucked up the ability to do that. This should fix that.
I wasn't able to think of a way to populate `Build.TestResultListSummary` in the same DB request as getting them (`buildModule.getBuild` and …
=> Fixed N+1 Build and TestResult fetch issue

CHANGELOG.md, database_models.go, migrations.go, pkg/model/database/database.go, provider.go
Removed field `Provider.UploadURL` and all references to it.
Added migration to remove DB column `provider.upload_url`
This field was unused and mostly lead to confusion.
Tried building wharf-web after the change but it wouldn't pass because `MainProvider.uploadUrl` from the previous swag definitions was used at `src/app/providers/providers.service.ts:L50`.
The change of `id` -> `Id` from #76 also causes the build to fail because of the auto-generated names for the endpoint functions, so I believe a MAJOR version bump is in order.
--
Closes #56.
=> Removed Provider.UploadURL

wharf-api-config.yml
- Added `wharf-api-config.yml`
Using the same values as from <https://github.com/iver-wharf/wharf-docker-compose>, but laid out in the YAML format that Wharf supports.
This makes local development easier, as you can run `make serve`, `go run .`, or run the wharf-api with debugging through your IDE. Much simpler than advertised in <https://iver-wharf.github.io/#/development/debugging-in-goland>
Best thing is that you don't have to rebuild the docker image just to try out your new changes, as `go run .` is much faster than `docker build`.
Will apply similar configs to the other repos if this gets merged.
=> Added config for local dev purpose

Makefile
- Skip `swag init` in Makefile if the `docs/docs.go` file exist
- Added `swag-force` target to Makefile that runs even if the `docs/docs.go` file exists
This makes `make serve`, `make tests`, etc more useful, by only running if needed, as `swag init` takes so much time to run
=> Makefile: only run 'swag init' if needed

CHANGELOG.md, migrations.go, pkg/model/database/database.go
- Added custom migration code for migrating columns in PostgreSQL to add `NOT NULL`
- Changed all database fields that were non-pointers from `gorm:"nullable"` to `gorm:"not null;default:''"`
This adds consistency between the wharf-api and the database.
Some fields cannot be null, according to our database models, as we're using `string` and not `*string`. Because of this, GORM will never set the values to `NULL` in the database as it's solely relying on the value in Go. In other words: for all the changed fields in the database models, none *should* actually have the value `NULL` in the database, but instead only empty strings.
So the …
=> Migrate columns to `NOT NULL`

CHANGELOG.md, config.go, main.go
This adds a environment variable that allows setting a cors allowed origin. When this is set Authrization Bearer tokens will also be allowed to be sent. This overrides the allow all origins header. When sending credentials allow all origins is not allowed.
When sending credentials allow all origins is not allowed. The way the OICD login is set to work credentials need to be sent and will use the `authorization` header.
=> Allow cred/authorization header CORS

.codacy.yml
- Added `.codacy.yml`
This disables the duplication check for the `internal/deprecated/...` files in this repo.
I've just moved deprecated endpoints into that dir, in the plan of removing them on the next major version bump. So refactoring them to not have duplicated code with the `project.go`, `providers.go`, etc files in the repo root directory seems extremely superfluous to me.
Based off docs: https://docs.codacy.com/repositories-configure/codacy-configuration-file/
=> Added Codacy exclude_paths for deprecated package

CHANGELOG.md, internal/deprecated/branch.go
- Added missing `PUT /branches` registration in `internal/deprecated` package
Forgot to register the endpoint in #91
=> Added missing PUT /branches endpoint registration

pkg/model/database/database.go, pkg/orderby/column.go, pkg/orderby/example_test.go, pkg/orderby/orderby_test.go, pkg/orderby/slice.go, project.go, utils.go
- Added type `database.SafeSQLName`
- Changed in `project.go`, `util.go`, and `orderby.go` to use `database.SafeSQLName` instead
- Changed orderby.Parse to error on nil, where it before returned the field name instead which may or may not be an invalid SQL column name.
Having a designated type for the column names makes it harder to accidentally use a user input as the column name when creating SQL queries, such as in `util.go`.
This now creates a compilation error:
```go
var columnName database.SafeSQLName
sql := columnName + " LIKE ?"
```
=> Added database.SafeSQLName type

CHANGELOG.md, pkg/model/database/database.go, pkg/model/request/request.go, pkg/model/response/response.go, pkg/modelconv/projectconv.go
Added `RemoteProjectID` to all `Project` models.
Updated `projectconv.go` functions to support `RemoteProjectID`.
Required change to be able to store the remote project ID from remote providers.
---
Closes #12.
=> Added RemoteProjectID to Project structs

.dockerignore, .gitignore
- Changed .gitignore & .dockerignore to be more organized and ignore more types, such as `*.db`, `*.tar`, and `*.tar.gz` files
`*.db` files are created by Sqlite.
`*.tar` files are created here and there, but one use case I came across in #115 is when saving Docker images to disk to be analysed.
=> Updated .gitignore & .dockerignore

CHANGELOG.md, artifact.go, build.go, internal/deprecated/project.go, pkg/model/response/response.go, project.go, provider.go, test_result.go, token.go
- Changed test_result.go to use paginated responses
- Renamed slice field in paginated response to only be "list"
Having the fields be named differently is just a hassle if your client supports any kind of generics. While Go doesn't, we don't want to be an easily avoidable annoyance.
Changing the test_result.go endpoints was brought up in discussion <https://github.com/iver-wharf/wharf-api/pull/109#issuecomment-966894215>, and was done to keep consistency with the other GET endpoints
=> Paginated response fixes

CHANGELOG.md, branch.go, build.go, internal/deprecated/branch.go, internal/deprecated/build.go, main.go, pkg/model/request/request.go, project.go
- Moved "start build" endpoint to build.go and the `build` Swagger tag
- Deprecated all `/branch` and `/branches` endpoints in favor of `/project/{projectId}/branch` endpoints
- Deprecated `POST /project/{projectId}/{stage}/run` in favor of new `POST /project/{projectId}/build` endpoint
- Deprecated `PUT /build/{buildId}` in favor of new `PUT /build/{buildId}/status` endpoint
I left the new endpoints as "NOT IMPLEMENTED" to leave it to be implemented in a future PR.
Closes #14, closes #69
=> Move endpoints

CHANGELOG.md, project.go
- Fixed `GET /project` using `providerJSONToColumns` instead of `projectJSONToColumns`
Copy-paste typo in #109 at https://github.com/iver-wharf/wharf-api/pull/109/files#diff-5bd45f0b550e390a3e0aa2ce718715f311ca88105ce8bfce2e1c32c234bda60eL110-R108
Noted by @Alexamakans in: <https://github.com/iver-wharf/wharf-api/commit/dd0f4c593b81bd5b9f80d08d4ad5b7f2ada036e8#r60557365>
=> Fixed GET /project using providerJSONToColumns

artifact.go, branch.go, build.go, internal/deprecated/artifact.go, internal/deprecated/branch.go, internal/deprecated/build.go, internal/deprecated/project.go, internal/deprecated/provider.go, internal/deprecated/token.go, ping.go, project.go, provider.go, test_result.go, token.go, version.go
- Added `@description Added in x.y.z.` to all endpoints.
Just documenting all endpoints to have more ways to detect when an endpoint was added.
Took some time to dig these versions up from our old archived repos. Luckily in the early days of Wharf it was just 1 repo and the author pushed directly to master, so those parts were easy to track down :]
=> Document endpoint versions

.wharf-ci.yml, Dockerfile
- Changed deploy tag in `.wharf-ci.yml` to `:canary`
- Changed to use our internal Docker Hub registry caching proxy in Docker builds
- Fixed Wharf build step name in `.wharf-ci.yml`
Minor tweaks to make the Wharf builds work and be able to build Wharf itself.
~~The image tag name `:unstable` is up for debate. Perhaps `:canary`? Or simply `:latest`?~~ Changed to `:canary`.
Related to https://github.com/iver-wharf/iver-wharf.github.io/issues/80
This is the first PR I'm marking "Ready for review". Let's have all discussions in this PR to begin with, as the other PRs listed in the meta-issue above are basically just the same.
=> Changed .wharf-ci.yml for canary builds

CHANGELOG.md, go.mod, go.sum
- Updated to wharf-core v1.3.0 (https://github.com/iver-wharf/wharf-core/releases/tag/v1.3.0)
Keep the repos dependencies up-to-date
=> Updated to wharf-core v1.3.0

CHANGELOG.md, internal/deprecated/project.go
- Changed to use deprecated.PaginatedBuilds instead of response.PaginatedBuilds, taken from v4.2.0, where array field was named `builds` and not `list`
PR #118 changed the array field in the paginated results to be named `list` instead of the name of the type.
This broke backward compatibility. This PR restores that
=> Fixed PaginatedBuilds in deprecated getProjectBuildListHandler

.gitattributes, CHANGELOG.md, Dockerfile, deploy/update-version.sh
Shebang signature modified for docker runs. Had issues on docker windows.
This makes it easier to docker build on windows.
Also see similar changes:
- https://github.com/iver-wharf/wharf-web/pull/95
- https://github.com/iver-wharf/wharf-provider-azuredevops/pull/48
- https://github.com/iver-wharf/wharf-provider-github/pull/44
- https://github.com/iver-wharf/wharf-provider-gitlab/pull/39
- https://github.com/iver-wharf/wharf-api/pull/126
=> Fix windows docker build

CHANGELOG.md, config.go, go.mod, go.sum, main.go, oidc_middleware.go, utils_test.go
Requires merge of 
Added a slew of options for setting OIDC parameters for JWT token verification. Upon setting enable this will check will be enforced for requests sent to the api such that all requests not carrying a valid bearer token will fail.
This works in coalition with the coresponding frontend implementation https://github.com/iver-wharf/wharf-web/pull/70. Both PRs make up all the needed code to get basics for OIDC working.
=> Add OIDC access token validation

CHANGELOG.md, branch.go, build.go, internal/deprecated/build.go, pkg/model/request/request.go, pkg/model/response/response.go, pkg/modelconv/branchconv.go, project.go, utils.go, utils_gorm.go
- Added checkProjectExistsByID & checkBuildExistsByID
- Implemented `GET /project/{projectId}/branch`
- Implemented `POST /project/{projectId}/branch`
- Implemented `PUT /build/{buildId}/status`
- Updated "NOT IMPLEMENTED YET" -> "NOT IMPLEMENTED" in deprecated endpoint
PR #120 marked some endpoints as deprecated and added new placeholder endpoints that should be used instead, but only returned "501 Not Implemented".
This PR adds implementation for them.
Closes https://github.com/iver-wharf/wharf-api/milestone/1. Yes, the final effort for RFC-0016
=> Implemented endpoints from #120

CHANGELOG.md, pkg/model/database/database.go
- Moved GORM foreignKey tag from `Project.Overrides` to `ProjectOverrides.ProjectID`.
Fixes inability to insert projects into the database when using postgresql.
=> Fixed foreign key constraint

CHANGELOG.md, build.go
Added preloading of test result summaries and params when getting a list of builds.
Required to be able to show the test result list summary (currently generated from test result summaries when getting) in the builds list view in iver-wharf/wharf-web/pull/53 without making an extra request per build.
Params preloaded as well to match getting a single build, and so it can be wrapped in a function.
Keep the preloading, but empty the `TestResultSummaries` field after generating the `TestResultListSummary` to save bandwidth when there are many tests. Thoughts?
I feel this is more of a bugfix, as I believe the idea was to have …
=> Preload test result summaries and params when getting list of builds

CHANGELOG.md, engine.go, pkg/model/response/response.go
- Changed `response.EngineList.Default` to `.DefaultEngine`
Fixes Swagger generated TypeScript/JavaScript code where the field was named `_default` by Swagger-codegen as `default` is a keyword in JavaScript.
Closes #139
=> Renamed EngineList.Default -> .DefaultEngine

Dockerfile, Makefile, README.md, package.json
- Added targets to `Makefile` for linting and other utilities like cleaning
- Removed linting from NPM scripts in `package.json`
- Simplified linting docs
Moves focus from relying on NPM for all linting stuff over to Makefile.
Based on https://github.com/iver-wharf/wharf-cmd/pull/31
=> Moved linting to Makefile

.github/workflows/go-format.yml, .github/workflows/go-test.yml, CHANGELOG.md, Dockerfile, README.md, go.mod, go.sum
- Upgraded to Go v1.17 in:
- `go.mod` & `go.sum`
- Dockerfile
- GitHub Actions workflows
- README.md
There's some Go 1.17 features I want to use in #147. Good to stay up-to-date anyway.
We'll probably have to make this journey soon again with the upcoming 1.18 release, but one step at a time.
=> Upgraded to Go v1.17

CHANGELOG.md, Makefile, build.go
- Changed `status` and `statusId` to be slices instead of single values
This is to allow wharf-cmd-watchdog to query for non-finished builds, as any finished builds are in either status `Completed` or `Failed`, which the API didn't support querying for before this PR.
We use the `multi` collection format, meaning to specify multiple values you specify the query parameter multiple times, such as:
```http
GET /api/build?status=Scheduling&status=Running
```
Because of this, the parameter only gains functionality and doesn't break backwards.
=> Changed build status query to accept arrays

build.go
- Changed the trigger URL building to use proper URL building.
Less prone to glitches and security vulnerabilities.
For example, if the engine URL before had a fragment, then it ruined the URL building:
```
http://jenkins.local/trigger#foo
// got turned into:
http://jenkins.local/trigger#foo?token=abc&stage=def&environment=etc
```
While now it correctly edits the correct part:
```
http://jenkins.local/trigger#foo
// now gets turned into:
http://jenkins.local/trigger?token=abc&stage=def&environment=etc#foo
```
=> Fixed URL query building

CHANGELOG.md, migrations.go
- Fixed failing migrations caused by foreign key constraints
I was comparing v5.0.0 and v5.1.0 in https://github.com/iver-wharf/wharf-api/compare/v5.0.0...v5.1.0diff-7807f0304222cb1bf359da44be1f2d3ce9beeea04d8c499192a46da74c3af820 and saw that one key difference is that I in #144 removed the double-migration, first without foreign key constraints, and then again with them.
It turns out our foreign key constraints has some circular dependencies. Fixing the database relations is postponed into #146. This PR is a band-aid fix.
I've now properly tested this in docker-compose using Postgres, as I should've done before.
Closes #160
=> Added back foreign key constrain-less migration

CHANGELOG.md, pkg/model/database/database.go
- Changed to rely on default constraint names in database types instead of overriding it
GORM apparently got confused when we specified the foreign key column name. It wrongly associated the `Token.TokenID` column instead of the `Project.TokenID` and `Provider.TokenID` etc.
This whole confusion seems to be because GORM was updated between wharf-api v5.0.0 and v5.1.0.
My love for GORM is decreasing more and more as time goes on. It's overall just quite unstable in its behaviour. This fight about foreign key constraint names we've fought before in a previous update. Now we tackle it again.
```console
$ \d token
Table "public.token"
Column   | …
```
=> Rely on default constraint names

CHANGELOG.md
- \[x] I've updated the `(WIP)` tag to today's date in `CHANGELOG.md`
- \[x] I've added the `release` label to this PR
- Fixed bug of failing migrations that was introduced in v5.1.0. (#161, #163)
Follow the step-by-step guide found here:
<https://iver-wharf.github.io/#/development/releasing-a-new-version?id=merging-a-release-pr>
=> Release v5.1.1

CHANGELOG.md
- \[x] I've updated the `(WIP)` tag to today's date in `CHANGELOG.md`
- \[x] I've added the `release` label to this PR
- Fixed token in trigger URL used in HTTP request getting redacted, instead of only the copy that is logged. (#166)
Follow the step-by-step guide found here:
<https://iver-wharf.github.io/#/development/releasing-a-new-version?id=merging-a-release-pr>
=> Release v5.1.2

CHANGELOG.md, utils_gin.go
- Disabled the auto-JSON indent in HTTP responses for web browsers
Forgot that AJAX requests contains the browser's user agent, so the requests that wharf-web did was indented.
=> Disabled auto indent for desktops

go.mod
- Reorganized so all non-indirect and indirect are in their respective `require` blocks inside go.mod
Thought `go mod tidy` did this for us, but appears not when dependencies goes from `// indirect` to not.
=> Reorganized go.mod

CHANGELOG.md, grpc.go
- Fixed gRPC logs stream ignoring logs if writer is slow.
The logs coming from wharf-cmd-worker -> wharf-cmd-aggregator -> wharf-api are not a steady stream. The previous implementation failed as soon as there was a pause in the logs stream.
This fixes that.
=> Fix grpc logs stream skipping if slow

CHANGELOG.md, engine.go, pkg/model/response/response.go
- Added `response.Engine.API` field, using `CIEngineConfig.API`
Good info to provide. Seems to have forgotten to add it to the response when I added the API field to CIEngineConfig
=> Added engine API ID in response

CHANGELOG.md, pkg/model/database/database.go
- Fixed `SafeSQLName` messing up GORM `.Where` statements
In GORM:
```go
db.Where("name IN ?", []any{"a", "b", "c"})
```
Is a shortcut for:
```go
db.Where(db.Raw("name IN ?", []any{"a", "b", "c"}))
```
But that only works if the first argument is a string.
It was not a string, it was a `SafeSQLName`, which was based on a string, but that didn't GORM understand.
Now `SafeSQLName` is a type alias instead of it's own type, so reflection doesn't see them as different types.
=> Fixed SafeSQLName not getting read correctly
